### PR TITLE
#51 add onAnimationReady callback

### PR DESCRIPTION
**Pull request by glauberramos**
Implementation on onRest from react-motion. Added a property called onAnimationReady.

### CODE REVIEW

**Comment by nkbt** [comment]
Looks good, thanks heaps!
I think keeping `onRest` name would be preferable, since it is basically just the way to expose ReactMotion's one, to avoid any confusion. Especially considering there is a link to docs too.

Other then that - I'd happily merge it!

**Comment by glauberramos** [comment]
just updated it @nkbt

**Comment by nkbt** [comment]
Great, thank you!

**Comment by nkbt** [comment]
Published react-collapse@2.3.0

**Pull request merged**
