### PR TITLE
Fix backward compatibility with react 14

### LINKED ISSUE #173: 2.4.0 breaks support for previous versions of react
2.4.0 broke support for our version of React (currently 0.14.9).

### PR DESCRIPTION
**Pull request by nkbt**
Fixes #173

### CODE REVIEW

**Comment by nkbt** [comment]
I am doing this change to v2, so it unbreaks react 0.14 support. I checked with the latest react 15 and react 14 - works well without any warnings. So I expect this not to break any of existing code


Ping @Andarist and @DeeLindesay

**Comment by nkbt** [comment]
I had to still up to ^0.14.9, but since it had no breaking changes any existing codebase should be able to work fine with it. Due to `prop-types` thing.

**Comment by Andarist** [comment]
Fine by me, but i think this breaks some assumptions - Collapse being pure. ShouldComponentUpdate should be restored now I think

**Comment by nkbt** [comment]
I don't think it is actually an issue, it is probably giving some tiny performance improvement, but other then that - component itself should be ok with it.

If it works - then it is ok. V2 is unsupported for a very long time now anyway. Unfortunately I did not properly publish V3 for a while and it bites me now =(

If there will be issues related to the purity of this component, them we can fix it separately.

**Comment by DeeLindesay** [comment]
Thanks for this.

I think it would have been reasonable to say that v2 would not be updated to work with react 15 and expect projects to go to v4 when updating react.  The issue really was adding a breaking change as a minor upgrade, which is unexpected.

Your efforts are much appreciated though!

**Pull request merged**
