### PR TITLE
Overflow hidden, when isOpened=true

### PR DESCRIPTION
**Pull request by Frumcheg**
Hi Nik! Thank you for this component!

But i found and fix little bug.

When i set prop `isOpened={true}`, component will be opened with this style:
`overflow: hidden; height: someHeight`.

So, if i have some `<div></div>` inside `<Collapse>` with `position: absolute` and height or width bigger then `<Collapse>`, `<div></div>` will be clipped :(.

This is unexpected, because when i close element once and open again, i see only
`height: someHeight` on node and everything is ok.

### CODE REVIEW

**Comment by nkbt** [comment]
> height: isOpened
This would set height to true which does not seem to be correct :(

Thanks for PR!

PS I'm going on holiday tomorrow morning for a week. Hopefully will have some internet to follow up

**Comment by Frumcheg** [comment]
> height: isOpened

Sure, gonna be `'auto'` in this case.

**Comment by nkbt** [comment]
Hi, @Frumcheg, I've updated code a bit, since `fixedHeight` should not use `height: auto`. It is fixed height =).

**Comment by nkbt** [comment]
```
+ react-collapse@2.2.2
```

https://github.com/nkbt/react-collapse/releases/tag/v2.2.2

**Pull request closed without merging**
